# Generated by Django 4.2.11 on 2024-04-19 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('logs', models.JSONField(blank=True, default=None, null=True)),
                ('day_calories', models.FloatField(blank=True, default=None, null=True)),
                ('day_protein', models.FloatField(blank=True, default=None, null=True)),
                ('day_carbs', models.FloatField(blank=True, default=None, null=True)),
                ('day_sugar', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
