# Generated by Django 4.2.11 on 2024-04-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0002_rename_meallogs_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='day_fats',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
