# Generated by Django 4.2.11 on 2024-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0003_meallog_day_fats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
