# Generated by Django 4.2.11 on 2024-04-22 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0004_alter_meallog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 22), unique=True),
        ),
    ]
