# Generated by Django 4.2.11 on 2024-04-22 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0005_alter_meallog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 4, 36, 39, 540927, tzinfo=datetime.timezone.utc), unique=True),
        ),
    ]
