# Generated by Django 4.2.11 on 2024-04-22 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0007_alter_meallog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
