# Generated by Django 4.2.11 on 2024-04-22 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0009_alter_meallog_day_calories_alter_meallog_day_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
