# Generated by Django 4.2.11 on 2024-06-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tc',
            new_name='is_verified',
        ),
    ]
