# Generated by Django 4.2.11 on 2024-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_tc_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=6969),
        ),
    ]
