# Generated by Django 4.2.11 on 2024-06-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_userotp_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=6969, null=True),
        ),
    ]
