version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: djangoapp
    build: .
    env_file: .env
    command: ["sh", "./django.sh"]
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/static
    depends_on:
      - web

volumes:
  postgres_data: {}
