apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: cw-backend
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: cal-wise-back
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: cal-wise-back
    spec:
      initContainers:
      - name: backend-migrations
        # Run this image
        image: tusshar17/calorie-wise-backend:01
        command: ["python", "manage.py", "migrate"]
        env:
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_PASSWORD
          - name: PG_DB
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_DB
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_PORT
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_HOST
      containers:
      - name: backend-container
        # Run this image
        image: tusshar17/calorie-wise-backend:01
        ports:
        - containerPort: 8000
        env:
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_PASSWORD
          - name: PG_DB
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_DB
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_PORT
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_HOST

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-cw-backend
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: cal-wise-back
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer

