apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: cal-wise-db
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: cal-wise-db
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: cal-wise-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: pg-config
                key: PG_DB
        volumeMounts:
        - mountPath:  /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-cw-db
spec:
  ports:
    # Accept traffic sent to port 80
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: cal-wise-db
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi