# Generated by Django 4.2.2 on 2024-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightrecord',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
