# Generated by Django 4.2.11 on 2024-04-16 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serving_size_in_g', models.FloatField(default=100)),
                ('calories', models.FloatField()),
                ('protein_in_g', models.FloatField()),
                ('carbs_in_g', models.FloatField()),
                ('fats_in_g', models.FloatField()),
                ('sugar_in_g', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
