# Generated by Django 4.2.11 on 2024-04-25 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('height_in_ft', models.FloatField()),
                ('starting_weight_in_kg', models.FloatField()),
                ('pal', models.FloatField()),
                ('weekly_goal', models.FloatField()),
                ('goal_weight', models.IntegerField()),
                ('goal_calories', models.FloatField()),
                ('goal_protein', models.FloatField()),
                ('goal_carbs', models.FloatField()),
                ('goal_fats', models.FloatField()),
                ('goal_sugar', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
