# Generated by Django 3.2.25 on 2024-04-29 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_in_inches', models.IntegerField()),
                ('starting_weight_in_kg', models.FloatField()),
                ('pal', models.FloatField()),
                ('weekly_goal', models.FloatField()),
                ('goal_weight', models.FloatField()),
                ('goal_calories', models.IntegerField()),
                ('goal_protein', models.IntegerField()),
                ('goal_carbs', models.IntegerField()),
                ('goal_fats', models.IntegerField()),
                ('goal_sugar', models.IntegerField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
