# Generated by Django 4.2.11 on 2024-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
