# Generated by Django 4.2.11 on 2024-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_setting', '0003_rename_height_in_ft_goal_height_in_inches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_sugar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='height_in_inches',
            field=models.IntegerField(),
        ),
    ]
