# Generated by Django 3.2.25 on 2024-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_setting', '0004_alter_goal_goal_calories_alter_goal_goal_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
